# Generated by Django 3.0.8 on 2020-07-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ['nombre_marca'],
            },
        ),
        migrations.CreateModel(
            name='Marca_Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uno', models.CharField(max_length=50)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automoviles.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'tipo',
                'verbose_name_plural': 'tipos',
                'ordering': ['nombre_tipo'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_modelo', models.CharField(max_length=50)),
                ('marca_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automoviles.Marca_Tipo')),
            ],
            options={
                'verbose_name': 'modelo',
                'verbose_name_plural': 'modelos',
                'ordering': ['nombre_modelo'],
            },
        ),
        migrations.AddField(
            model_name='marca_tipo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automoviles.Tipo'),
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='pictures/autos')),
                ('caracteristicas', models.FileField(upload_to='files/autos')),
                ('marca_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automoviles.Marca_Tipo')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automoviles.Modelo')),
            ],
        ),
    ]
