# Generated by Django 3.0.8 on 2020-07-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automoviles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca_tipo',
            name='uno',
        ),
    ]
